### ISSUE TITLE
Empty Question Category

### ISSUE THREAD

**Issue by behoof** [moodleou/moodle-atto_embedquestion#1]
L.s.

The question category remains empty, while the question is there in  a category and is working in a quiz.

Bert

**Comment by timhunt** [comment]
Did you follow all the instructions? https://github.com/moodleou/moodle-filter_embedquestion/blob/master/internaldoc/functionality.txt#L27

You need to put an [ID:...] on both the category and the questions you want to embed.

The plugins definitely works for us.

**Comment by behoof** [comment]
Tim,

That did the job!

Marvelous functionality!

Bert

Van: Tim Hunt <notifications@github.com>
Beantwoorden - Aan: moodleou/moodle-atto_embedquestion <reply@reply.github.com>
Datum: vrijdag 17 augustus 2018 om 13:11
Aan: moodleou/moodle-atto_embedquestion <moodle-atto_embedquestion@noreply.github.com>
CC: "bert@vanderhooft.com" <bert@vanderhooft.com>, Author <author@noreply.github.com>
Onderwerp: Re: [moodleou/moodle-atto_embedquestion] Empty Question Category (#1)


Did you follow all the instructions? https://github.com/moodleou/moodle-filter_embedquestion/blob/master/internaldoc/functionality.txt#L27

You need to put an [ID:...] on both the category and the questions you want to embed.

The plugins definitely works for us.

**Comment by timhunt** [comment]
Closing this issue, following the last comment.
