### ISSUE TITLE
Atto_embedquestion not picking up questions from question bank

### ISSUE THREAD

**Issue by will-bulluck** [moodleou/moodle-atto_embedquestion#2]
Hey there

We are using the embed questions plugins (filter and atto) on Moodle 3.9.12 and when you go to embed a question the plugin doesn't seem to recognize there are questions in the course.

Your assistance is greatly appreciated,

Will Bulluck
Tier One Support Specialist
will.bulluck@learningpool.com

**Comment by timhunt** [comment]
Have you added idnumbers to the questions and categories? https://github.com/moodleou/moodle-filter_embedquestion/blob/main/internaldoc/functionality.txt

**Comment by will-bulluck** [comment]
@timhunt Yes I have. I made the ID 007

**Comment by will-bulluck** [comment]
This can be closed, we were not inputting a category ID

**Comment by timhunt** [comment]
Thanks for letting us know you have solved the problem.
