### ISSUE TITLE
dmlreadexception on new install in Moodle 4.1

### ISSUE THREAD

**Issue by arborrow** [moodleou/moodle-atto_embedquestion#3]
Greetings Tim! 

I was attempting to install the embedquestion filter and atto plugin on a 4.1 site (under IIS, PHP 7.4, MSSQL) and when I click on the icon to embed a question in the atto editor I get a dmlreadexception. 

Any thoughts or ideas? I figured I would check if anything sounds familiar before trying to troubleshoot a bit further myself. 

Peace - Anthony

**Comment by timhunt** [comment]
Please turn on Deubgging, and give the full error message.

**Comment by arborrow** [comment]
Thanks Tim, here's what debugger reveals:

SQLState: 42000<br>
Error Code: 8120<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column 'mdl_question_categories.idnumber' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>


                    SELECT qc.id, qc.name, qc.idnumber, COUNT(q.id) AS count

                      FROM mdl_question_categories qc
                      JOIN mdl_question_bank_entries qbe ON qbe.questioncategoryid = qc.id
                                    AND qbe.idnumber IS NOT NULL 
                      JOIN mdl_question_versions qv ON qv.questionbankentryid = qbe.id AND qv.version = (
                                    SELECT MAX(version)
                                      FROM mdl_question_versions
                                     WHERE questionbankentryid = qbe.id AND status = N'ready'
                                    )
                      JOIN mdl_question q ON q.id = qv.questionid

                     WHERE qc.contextid = '22'
                       AND qc.idnumber IS NOT NULL

                  GROUP BY qc.id, qc.name
                    HAVING COUNT(q.id) > 0
                  ORDER BY qc.name
                    
[array (
  0 => 'ready',
  1 => 22,
)]
Error code: dmlreadexception
* line 494 of \lib\dml\moodle_database.php: dml_read_exception thrown
* line 331 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
* line 438 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
* line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
* line 983 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
* line 240 of \filter\embedquestion\classes\utils.php: call to sqlsrv_native_moodle_database->get_records_sql()
* line 62 of \filter\embedquestion\classes\form\embed_options_form.php: call to filter_embedquestion\utils::get_categories_with_sharable_question_choices()
* line 214 of \lib\formslib.php: call to filter_embedquestion\form\embed_options_form->definition()
* line 75 of \lib\editor\atto\plugins\embedquestion\lib.php: call to moodleform->__construct()
* line 8064 of \lib\moodlelib.php: call to atto_embedquestion_output_fragment_questionselector()
* line 423 of \lib\external\externallib.php: call to component_callback()
* line 262 of \lib\externallib.php: call to core_external::get_fragment()
* line 81 of \lib\ajax\service.php: call to external_api::call_external_function()

**Comment by arborrow** [comment]
Off the top of my head, it looks to be one of those typical SQL server configuration setting type of issues possibly related to strict grouping.

**Comment by timhunt** [comment]
Thanks. That makes it clear.

Good databases (that is, Postgres, which we use) know that if you have grouped by GROUP BY qc.id, where id is the primary key of that table, then you have grouped by all the rows in that table.

I guess MS SQL has not been taught that. I just need to add qc.idnumber to the GROUP BY.

**Comment by timhunt** [comment]
So, the acual issue is in filter_embed question, and the fix is here: https://github.com/moodleou/moodle-filter_embedquestion/commit/ce572dcd68e3a8ee31358df8fe192da11afd24f3

Note, I am not currently in a position to release the latest version of all these plugins to the plugins DB. Sorry.

**Comment by arborrow** [comment]
@timhunt Many thanks for the prompt reply, I tested the patch and it worked great. I agree that MSSQL is probably less than an ideal database for Moodle but it is something I have inherited and haven't taken the time to change. Peace - Anthony
